### ISSUE TITLE
unable to reproduce autoweka results

### ISSUE THREAD

**Issue by alex72bis** [dsibournemouth/autoweka#11]
Hello fellow researchers,

I classified my dataset through the Auto-Weka classifier and it gave me the Random Forest but I was unable to set these parameters in the weka GUI nor to test it in the command line (I am a novice user). Could you please help me. 
The results of the autoweka are:

Auto-WEKA result:
best classifier: weka.classifiers.trees.RandomForest
arguments: [-I, 10, -K, 0, -depth, 0]
attribute search: null
attribute search arguments: []
attribute evaluation: null
attribute evaluation arguments: []
metric: errorRate
estimated errorRate: 0.0125
training time on evaluation dataset: 0.032 seconds

You can use the chosen classifier in your own code as follows:

Classifier classifier = AbstractClassifier.forName("weka.classifiers.trees.RandomForest", new String[]{"-I", "10", "-K", "0", "-depth", "0"});
classifier.buildClassifier(instances);

Correctly Classified Instances          76               95      %
Incorrectly Classified Instances         4                5      %
Kappa statistic                          0.8837
Mean absolute error                      0.1462
Root mean squared error                  0.2216
Relative absolute error                 33.2202 %
Root relative squared error             47.3194 %
Total Number of Instances               80     

=== Confusion Matrix ===

  a  b   <-- classified as
 53  1 |  a = si
  3 23 |  b = no

=== Detailed Accuracy By Class ===

                 TP Rate  FP Rate  Precision  Recall   F-Measure  MCC      ROC Area  PRC Area  Class
                 0,981    0,115    0,946      0,981    0,964      0,885    0,992     0,995     si
                 0,885    0,019    0,958      0,885    0,920      0,885    0,992     0,979     no
Weighted Avg.    0,950    0,084    0,950      0,950    0,949      0,885    0,992     0,990     

Temporary run directories:
C:\Users\Win\AppData\Local\Temp\autoweka1947462785079757973\

For better performance, try giving Auto-WEKA more time.
Tried 333 configurations; to get good results reliably you may need to allow for trying thousands of configurations.

**Comment by DraXus** [comment]
Hi @alex72bis,

If you'd like to run your configuration in Weka, go to "Classify", then right click on top of selected configuration and select "Enter configuration...". This will open a text box where you need to paste your configuration: `weka.classifiers.trees.RandomForest -I 10 -K 0 -depth 0`. Then click OK and you can now run it with your data.

![image](https://user-images.githubusercontent.com/2436/65956825-98dfe180-e44b-11e9-84bf-f69bf7b1c1ff.png)

**Comment by alex72bis** [comment]
Actually I tried several time, but after I clicked the ok button the configuration line is completely different (-P 100 - I 10 -num-slots 1 -K 0 -M 1.0 - v 0.001 -s 1) and the results produced are very different from the autoweks (correctly instances 72.5 % vs 95%!)

________________________________
Da: Manuel Martín <notifications@github.com>
Inviato: martedì 1 ottobre 2019 13:01
A: dsibournemouth/autoweka <autoweka@noreply.github.com>
Cc: alex72bis <aannovazzi@hotmail.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [dsibournemouth/autoweka] unable to reproduce autoweka results (#11)


Hi @alex72bis<https://github.com/alex72bis>,

If you'd like to run your configuration in Weka, go to "Classify", then right click on top of selected configuration and select "Enter configuration...". This will open a text box where you need to paste your configuration: weka.classifiers.trees.RandomForest -I 10 -K 0 -depth 0. Then click OK and you can now run it with your data.

[image]<https://user-images.githubusercontent.com/2436/65956825-98dfe180-e44b-11e9-84bf-f69bf7b1c1ff.png>

**Comment by alex72bis** [comment]
Weka 3.8.3
Autoweka 2.6.1
________________________________
Da: Manuel Martín <notifications@github.com>
Inviato: martedì 1 ottobre 2019 17:58:30
A: dsibournemouth/autoweka <autoweka@noreply.github.com>
Cc: alex72bis <aannovazzi@hotmail.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [dsibournemouth/autoweka] unable to reproduce autoweka results (#11)


What versions of Auto-WEKA and WEKA are you using?

**Comment by DraXus** [comment]
@alex72bis oh, this is a different version that we got in this repo. So probably a few things have changed since then. Please ask in https://github.com/automl/autoweka which has the latest version of Auto-WEKA.
