### ISSUE TITLE
Problem in running Auto Weka

### ISSUE THREAD

**Issue by PriyeshLakar** [dsibournemouth/autoweka#8]
Hello team,

I am facing some problem in running Auto Weka on my machine. Please can you guys help me out and guide me with the same.

Steps followed:

1) Simply, downloaded the jar from this GitHub.
2) Double clicked on the autoweka.jar file.
Error : On click the Wizard button in auto weka launcher,  a new auto wizard box appears. There I uploaded one of the data sets and on clicking the run experiment I get the following error: 

"Failed to open the experiment". and when I click on Show stack trace then I get the following error: 

java.lang.NullPointerException
	at autoweka.ui.TrainedModelRunner.openExperiment(TrainedModelRunner.java:115)
	at autoweka.ui.Wizard$1.update(Wizard.java:81)
	at autoweka.ui.ExperimentRunner$1.run(ExperimentRunner.java:123)
	at java.lang.Thread.run(Thread.java:748)

I am trying to install in my MAC machine, with java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11).

Any help is highly appreciated. Thanks in advance.

**Comment by DraXus** [comment]
Hi @PriyeshLakar 

Thanks for reporting this issue. I'm currently looking into it. I'll update this ticket once I've got more information.

**Comment by PriyeshLakar** [comment]
Hi DraXus,

Thank you for responding. Just a small heads up, sometimes while running I even get this error. Please let me know if I am doing something wrong. Again, I have just downloaded the jar and tried to install it. While running it throws up these errors.

Error: 

Failed to create experiment.
./params/attribselection/eval/ is not a valid directory.

Trace Stack:

java.lang.RuntimeException: ./params/attribselection/eval/ is not a valid directory
	at autoweka.ApplicabilityTester.getApplicable(ApplicabilityTester.java:145)
	at autoweka.ApplicabilityTester.getApplicableAttributeEvaluators(ApplicabilityTester.java:126)
	at autoweka.ExperimentConstructor.loadAttributeSelectors(ExperimentConstructor.java:309)
	at autoweka.ExperimentConstructor.run(ExperimentConstructor.java:202)
	at autoweka.ExperimentConstructor.buildSingle(ExperimentConstructor.java:153)
	at autoweka.ui.Wizard.buildExperiment(Wizard.java:137)
	at autoweka.ui.Wizard.runExperiment(Wizard.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.javabuilders.util.BuilderUtils.invokeCallerEventMethods(BuilderUtils.java:427)
	at org.javabuilders.swing.handler.event.CommonActionListenerHandler$2.actionPerformed(CommonActionListenerHandler.java:77)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by DraXus** [comment]
That second error seems to be that it's not finding the right folder. Please download the whole repository and not only the .jar file. Then, try to run it again.

Regarding your first error, I haven't fixed it yet because I'm finding a problem with SMAC library. Please do the following to use a newer version in the mean time:
1. Launch Auto-WEKA
2. Click on Experiment Builder
3. Follow the steps until Experiment Settings tab.
4. In "Optimisation method" select SMAC and click Edit button.
5. In "SMAC executable" click Open button and find the file "smac-v2.06.01-development-619/smac"
6. Close the SMAC options and click Save button.
7. Go to Experiment Runner
8. In "Experiment Folder" find the experiment folder you just created
9. Click Run button.

Please let me know if this is approach is working for you.

**Comment by PriyeshLakar** [comment]
The problem is when I download the whole repository, I don't find any jar file in it. What should I do then? Do I need to build everything again?

**Comment by DraXus** [comment]
That's very weird. Please use this link: https://github.com/dsibournemouth/autoweka/archive/master.zip

**Comment by PriyeshLakar** [comment]
Hello Draxus,

**Comment by PriyeshLakar** [comment]
Hello Draxus,

Yes, the downloads seem to be accurate via this link. Thank you for providing me the link. Now, the error two is resolved but I am still facing issue regarding error 1. The step pf selecting the SMAC executables which you mentioned in Step 5 is by default referring to the same smac file which is already selected i.e. "smac-v2.06.01-development-619/smac". After following all the mentioned steps I finally got the following error at the end i.e. after Step 9.

/Users/plakar/Downloads/autoweka-master 3/experiments/Priyesh_v2 Priyesh_v2
'smac-v2.06.01-development-619/smac' '--seed' '0' '--scenarioFile' 'autoweka.scenario' '--logModel' 'false' '--adaptiveCapping' 'false' '--runGroupName' 'autoweka' '--terminate-on-delete' '/Users/plakar/Downloads/autoweka-master 3/experiments/Priyesh_v2//out/runstamps/0.stamp' '--kill-runs-on-file-delete' '/Users/plakar/Downloads/autoweka-master 3/experiments/Priyesh_v2//out/runstamps/0.stamp' '--initialIncumbent' 'RANDOM' '--initialN' '1' '--acq-func' 'EI' '--executionMode' 'SMAC' 
Exception in thread "main" java.lang.NoClassDefFoundError: weka/core/Instance
	at autoweka.Experiment.main(Experiment.java:235)
	at autoweka.tools.ExperimentRunner.main(ExperimentRunner.java:47)
Caused by: java.lang.ClassNotFoundException: weka.core.Instance
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

Looking forward to your reply.

**Comment by DraXus** [comment]
Sorry, my bad. The path should be "smac-v2.10.03-master-778/smac".

**Comment by PriyeshLakar** [comment]
Okay, no problem but on running I am still getting something like this :

**Comment by PriyeshLakar** [comment]
/Users/plakar/Downloads/autoweka-master 3/experiments/Priyesh_v3 Priyesh_v3
'smac-v2.10.03-master-778/smac' '--seed' '0' '--scenarioFile' 'autoweka.scenario' '--logModel' 'false' '--adaptiveCapping' 'false' '--runGroupName' 'autoweka' '--terminate-on-delete' '/Users/plakar/Downloads/autoweka-master 3/experiments/Priyesh_v3//out/runstamps/0.stamp' '--kill-runs-on-file-delete' '/Users/plakar/Downloads/autoweka-master 3/experiments/Priyesh_v3//out/runstamps/0.stamp' '--initialIncumbent' 'RANDOM' '--initialN' '1' '--acq-func' 'EI' '--executionMode' 'SMAC' 
Exception in thread "main" java.lang.NoClassDefFoundError: weka/core/Instance
	at autoweka.Experiment.main(Experiment.java:235)
	at autoweka.tools.ExperimentRunner.main(ExperimentRunner.java:47)
Caused by: java.lang.ClassNotFoundException: weka.core.Instance
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

**Comment by PriyeshLakar** [comment]
Can't we do auto selection just by selecting Wizard button? 
Draxus, can that be fixed?

**Comment by DraXus** [comment]
Yes, I'm working on a fix. Please bear with me. It will take some time, as I'm no longer working in this project.

**Comment by PriyeshLakar** [comment]
Yes, no problem DraXus. I will wait for your reply.

**Comment by DraXus** [comment]
@PriyeshLakar I've released a fix. Please get the full repository again from https://github.com/dsibournemouth/autoweka/archive/master.zip and run `java -jar autoweka.jar`. Wizard should be working fine now, please let me know if this works fine for you.

**Comment by PriyeshLakar** [comment]
@DraXus Thank you so much, now the code is running perfectly through the command line. One last thing it fails for the data set which is there in the zip file. I tried running on the iris data set too and I got stuck in a similar situation. Please can you guide me with this last step, I will be deeply grateful to you. I have shared the error which I am getting. 

Console Output:

internal ID: 0x000D), with mean quality: 1.0E9; estimate based on 1 runs.
[INFO ] Sample call for new incumbent config 1 (internal ID: 0x000D): 
cd /Users/plakar/Downloads/autoweka-master4/wizardexperiments/MyExperiment/.; /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/bin/java -Xmx500m -cp /Users/plakar/Downloads/autoweka-master4/autoweka.jar autoweka.smac.SMACWrapper -prop datasetString=testArff=__dummy____COLONESCAPE__:type=trainTestArff__COLONESCAPE__:trainArff=/Users/plakar/Downloads/autoweka-master4/datasets/creditg.arff:instanceGenerator=autoweka.instancegenerators.CrossValidation:resultMetric=errorRate -prop initialIncumbent=RANDOM:acq-func=EI -wrapper seed=0:numFolds=10:fold=0 0 3600.0 2147483647 -1 -_1_0_W 'weka.classifiers.meta.FilteredClassifier' -_1_0_W_0_DASHDASH 'REMOVED' -_1_2_W 'weka.classifiers.bayes.BayesNet' -_1_2_W_0_DASHDASH 'REMOVED' -_1_2_W_1__wcbbn_00_D 'REMOVED' -_1_2_W_1__wcbbn_01_A_QUOTE_START_Q 'weka.classifiers.bayes.net.search.local.K2' -_1_2_W_1__wcbbn_01_Q__wcbnslk_00_N 'REMOVED' -_1_2_W_1__wcbbn_01_Q__wcbnslk_01_INT_P '31097' -_1_2_W_1__wcbbn_01_Q__wcbnslk_02_R 'REMOVED' -_1_2_W_1__wcbbn_01_Q__wcbnslk_03_mbc 'REMOVE_PREV' -_1_2_W_1__wcbbn_01_Q__wcbnslk_04_S 'AIC' -_1_2_W_1__wcbbn_01__QUOTE_END 'REMOVED' -aseval__wasrfae_00_0_INT_K '15' -aseval__wasrfae_01_1_W 'REMOVED' -aseval__wasrfae_02_2_INT_A '1' -assearch__wasr_00_0_T '8.143955649410623' -attributeeval 'weka.attributeSelection.ReliefFAttributeEval' -attributesearch 'weka.attributeSelection.Ranker' -attributetime '600.0' -targetclass 'weka.classifiers.meta.ClassificationViaRegression'  
[INFO ] Call (with token 0) : cd "/Users/plakar/Downloads/autoweka-master4/wizardexperiments/MyExperiment/." ;  /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/bin/java -Xmx500m -cp /Users/plakar/Downloads/autoweka-master4/autoweka.jar autoweka.smac.SMACWrapper -prop datasetString=testArff=__dummy____COLONESCAPE__:type=trainTestArff__COLONESCAPE__:trainArff=/Users/plakar/Downloads/autoweka-master4/datasets/creditg.arff:instanceGenerator=autoweka.instancegenerators.CrossValidation:resultMetric=errorRate -prop initialIncumbent=RANDOM:acq-func=EI -wrapper seed=0:numFolds=10:fold=6 0 3600.0 2147483647 -1 -_1_0_W 'weka.classifiers.meta.FilteredClassifier' -_1_0_W_0_DASHDASH 'REMOVED' -_1_2_W 'weka.classifiers.bayes.BayesNet' -_1_2_W_0_DASHDASH 'REMOVED' -_1_2_W_1__wcbbn_00_D 'REMOVED' -_1_2_W_1__wcbbn_01_A_QUOTE_START_Q 'weka.classifiers.bayes.net.search.local.K2' -_1_2_W_1__wcbbn_01_Q__wcbnslk_00_N 'REMOVED' -_1_2_W_1__wcbbn_01_Q__wcbnslk_01_INT_P '31097' -_1_2_W_1__wcbbn_01_Q__wcbnslk_02_R 'REMOVED' -_1_2_W_1__wcbbn_01_Q__wcbnslk_03_mbc 'REMOVE_PREV' -_1_2_W_1__wcbbn_01_Q__wcbnslk_04_S 'AIC' -_1_2_W_1__wcbbn_01__QUOTE_END 'REMOVED' -aseval__wasrfae_00_0_INT_K '15' -aseval__wasrfae_01_1_W 'REMOVED' -aseval__wasrfae_02_2_INT_A '1' -assearch__wasr_00_0_T '8.143955649410623' -attributeeval 'weka.attributeSelection.ReliefFAttributeEval' -attributesearch 'weka.attributeSelection.Ranker' -attributetime '600.0' -targetclass 'weka.classifiers.meta.ClassificationViaRegression'  
[ERROR] The following algorithm call failed: cd "/Users/plakar/Downloads/autoweka-master4/wizardexperiments/MyExperiment/." ;  /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/bin/java -Xmx500m -cp /Users/plakar/Downloads/autoweka-master4/autoweka.jar autoweka.smac.SMACWrapper -prop datasetString=testArff=__dummy____COLONESCAPE__:type=trainTestArff__COLONESCAPE__:trainArff=/Users/plakar/Downloads/autoweka-master4/datasets/creditg.arff:instanceGenerator=autoweka.instancegenerators.CrossValidation:resultMetric=errorRate -prop initialIncumbent=RANDOM:acq-func=EI -wrapper seed=0:numFolds=10:fold=6 0 3600.0 2147483647 -1 -_1_0_W 'weka.classifiers.meta.FilteredClassifier' -_1_0_W_0_DASHDASH 'REMOVED' -_1_2_W 'weka.classifiers.bayes.BayesNet' -_1_2_W_0_DASHDASH 'REMOVED' -_1_2_W_1__wcbbn_00_D 'REMOVED' -_1_2_W_1__wcbbn_01_A_QUOTE_START_Q 'weka.classifiers.bayes.net.search.local.K2' -_1_2_W_1__wcbbn_01_Q__wcbnslk_00_N 'REMOVED' -_1_2_W_1__wcbbn_01_Q__wcbnslk_01_INT_P '31097' -_1_2_W_1__wcbbn_01_Q__wcbnslk_02_R 'REMOVED' -_1_2_W_1__wcbbn_01_Q__wcbnslk_03_mbc 'REMOVE_PREV' -_1_2_W_1__wcbbn_01_Q__wcbnslk_04_S 'AIC' -_1_2_W_1__wcbbn_01__QUOTE_END 'REMOVED' -aseval__wasrfae_00_0_INT_K '15' -aseval__wasrfae_01_1_W 'REMOVED' -aseval__wasrfae_02_2_INT_A '1' -assearch__wasr_00_0_T '8.143955649410623' -attributeeval 'weka.attributeSelection.ReliefFAttributeEval' -attributesearch 'weka.attributeSelection.Ranker' -attributetime '600.0' -targetclass 'weka.classifiers.meta.ClassificationViaRegression'  
[ERROR] The last 8 lines of output we saw were:
[ERROR] > Attribute selection completed
[ERROR] > Using the following attributes (4.761904761904762%)
[ERROR] > 0
[ERROR] > The target class is 0
[ERROR] > Training of classifier completed
[ERROR] > Training the classifier failed with the error: weka.classifiers.bayes.BayesNet: Cannot handle numeric class!
[ERROR] > Main Thread completed
[ERROR] > Result for ParamILS: CRASHED, 0.98178995, 0, 100.0, -1, EXTRA 0.0
[INFO ] Updated estimated mean quality of the same incumbent: 1.0E9; estimate now based on 2 runs.
[INFO ] Call (with token 0) : cd "/Users/plakar/Downloads/autoweka-master4/wizardexperiments/MyExperiment/." ;  /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/bin/java -Xmx500m -cp /Users/plakar/Downloads/autoweka-master4/autoweka.jar autoweka.smac.SMACWrapper -prop datasetString=testArff=__dummy____COLONESCAPE__:type=trainTestArff__COLONESCAPE__:trainArff=/Users/plakar/Downloads/autoweka-master4/datasets/creditg.arff:instanceGenerator=autoweka.instancegenerators.CrossValidation:resultMetric=errorRate -prop initialIncumbent=RANDOM:acq-func=EI -wrapper seed=0:numFolds=10:fold=6 0 3600.0 2147483647 -1 -_0__wcmlb_00_INT_I '71' -_0__wcmlb_01_h_HIDDEN '0' -_0__wcmlb_02_1_H '1' -_0__wcmlb_04_INT_R '5' -_0__wcmlb_05_f_HIDDEN '0' -_0__wcmlb_06_1_F '0' -_0__wcmlb_08_p_HIDDEN '0' -_0__wcmlb_09_1_P '100' -_0__wcmlb_11_L '1e50' -_0__wcmlb_12_S '1' -_1_0_W 'weka.classifiers.meta.FilteredClassifier' -_1_0_W_0_DASHDASH 'REMOVED' -_1_2_W 'weka.classifiers.functions.SMO' -_1_2_W_0_DASHDASH 'REMOVED' -_1_2_W_1__wcfsmo_00_C '1.1423354616652248' -_1_2_W_1__wcfsmo_01_N '2' -_1_2_W_1__wcfsmo_02_M 'REMOVE_PREV' -_1_2_W_1__wcfsmo_03_A_QUOTE_START_K 'weka.classifiers.functions.supportVector.PolyKernel' -_1_2_W_1__wcfsmo_03_K__wcfsvpk_00_E '4.59640169976281' -_1_2_W_1__wcfsmo_03_K__wcfsvpk_01_L 'REMOVE_PREV' -_1_2_W_1__wcfsmo_03__QUOTE_END 'REMOVED' -attributesearch 'NONE' -attributetime '600.0' -targetclass 'weka.classifiers.meta.LogitBoost'  
[ERROR] The following algorithm call failed: cd "/Users/plakar/Downloads/autoweka-master4/wizardexperiments/MyExperiment/." ;  /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/bin/java -Xmx500m -cp /Users/plakar/Downloads/autoweka-master4/autoweka.jar autoweka.smac.SMACWrapper -prop datasetString=testArff=__dummy____COLONESCAPE__:type=trainTestArff__COLONESCAPE__:trainArff=/Users/plakar/Downloads/autoweka-master4/datasets/creditg.arff:instanceGenerator=autoweka.instancegenerators.CrossValidation:resultMetric=errorRate -prop initialIncumbent=RANDOM:acq-func=EI -wrapper seed=0:numFolds=10:fold=6 0 3600.0 2147483647 -1 -_0__wcmlb_00_INT_I '71' -_0__wcmlb_01_h_HIDDEN '0' -_0__wcmlb_02_1_H '1' -_0__wcmlb_04_INT_R '5' -_0__wcmlb_05_f_HIDDEN '0' -_0__wcmlb_06_1_F '0' -_0__wcmlb_08_p_HIDDEN '0' -_0__wcmlb_09_1_P '100' -_0__wcmlb_11_L '1e50' -_0__wcmlb_12_S '1' -_1_0_W 'weka.classifiers.meta.FilteredClassifier' -_1_0_W_0_DASHDASH 'REMOVED' -_1_2_W 'weka.classifiers.functions.SMO' -_1_2_W_0_DASHDASH 'REMOVED' -_1_2_W_1__wcfsmo_00_C '1.1423354616652248' -_1_2_W_1__wcfsmo_01_N '2' -_1_2_W_1__wcfsmo_02_M 'REMOVE_PREV' -_1_2_W_1__wcfsmo_03_A_QUOTE_START_K 'weka.classifiers.functions.supportVector.PolyKernel' -_1_2_W_1__wcfsmo_03_K__wcfsvpk_00_E '4.59640169976281' -_1_2_W_1__wcfsmo_03_K__wcfsvpk_01_L 'REMOVE_PREV' -_1_2_W_1__wcfsmo_03__QUOTE_END 'REMOVED' -attributesearch 'NONE' -attributetime '600.0' -targetclass 'weka.classifiers.meta.LogitBoost'  
[ERROR] The last 4 lines of output we saw were:
[ERROR] > Training of classifier completed
[ERROR] > Training the classifier failed with the error: weka.classifiers.functions.SMO: Cannot handle numeric class!
[ERROR] > Main Thread completed
[ERROR] > Result for ParamILS: CRASHED, 0.42717698, 0, 100.0, -1, EXTRA 0.0
[INFO ] Call (with token 0) : cd "/Users/plakar/Downloads/autoweka-master4/wizardexperiments/MyExperiment/." ;  /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/bin/java -Xmx500m -cp /Users/plakar/Downloads/autoweka-master4/autoweka.jar autoweka.smac.SMACWrapper -prop datasetString=testArff=__dummy____COLONESCAPE__:type=trainTestArff__COLONESCAPE__:trainArff=/Users/plakar/Downloads/autoweka-master4/datasets/creditg.arff:instanceGenerator=autoweka.instancegenerators.CrossValidation:resultMetric=errorRate -prop initialIncumbent=RANDOM:acq-func=EI -wrapper seed=0:numFolds=10:fold=0 0 3600.0 2147483647 -1 -_0__wcmlb_00_INT_I '71' -_0__wcmlb_01_h_HIDDEN '0' -_0__wcmlb_02_1_H '1' -_0__wcmlb_04_INT_R '5' -_0__wcmlb_05_f_HIDDEN '0' -_0__wcmlb_06_1_F '0' -_0__wcmlb_08_p_HIDDEN '0' -_0__wcmlb_09_1_P '100' -_0__wcmlb_11_L '1e50' -_0__wcmlb_12_S '1' -_1_0_W 'weka.classifiers.meta.FilteredClassifier' -_1_0_W_0_DASHDASH 'REMOVED' -_1_2_W 'weka.classifiers.functions.SMO' -_1_2_W_0_DASHDASH 'REMOVED' -_1_2_W_1__wcfsmo_00_C '1.1423354616652248' -_1_2_W_1__wcfsmo_01_N '2' -_1_2_W_1__wcfsmo_02_M 'REMOVE_PREV' -_1_2_W_1__wcfsmo_03_A_QUOTE_START_K 'weka.classifiers.functions.supportVector.PolyKernel' -_1_2_W_1__wcfsmo_03_K__wcfsvpk_00_E '4.59640169976281' -_1_2_W_1__wcfsmo_03_K__wcfsvpk_01_L 'REMOVE_PREV' -_1_2_W_1__wcfsmo_03__QUOTE_END 'REMOVED' -attributesearch 'NONE' -attributetime '600.0' -targetclass 'weka.classifiers.meta.LogitBoost'

**Comment by DraXus** [comment]
Glad to hear it's working. There is no Exception in the log you shared, is there something missing during copy&paste?. Ignore the `[ERROR]` messages as that's normal, the process is running fine.

**Comment by PriyeshLakar** [comment]
But, then how do we check the output? Like, I thought this is a problem for us 

**[ERROR] > Training the classifier failed with the error: weka.classifiers.bayes.BayesNet: Cannot handle numeric class!**

The auto-weak should directly classify my data by choosing the right algorithm. Am I correct in my understanding?

**Comment by DraXus** [comment]
There is no need to check the log as it contains quite a lot of noise from SMAC. The selected classifier will be returned when the process finishes. For example, if you give 24 hours budget, you'd need to wait 24 hours until getting the final solution. The final solution is a WEKA classifier which will be shown in a new window. After that, you can use that WEKA configuration to classify your data.
