### ISSUE TITLE
Unable to save Experiment in Experiment Builder

### ISSUE THREAD

**Issue by skocbek** [dsibournemouth/autoweka#9]
Hi, 

I have been unable to save my experiments in Experiment Builder when I pre-choose filters and predictors. For example, I load the abalone dataset, select Normalize as the filter and SMO and ZeroG as predictors, and when I try to save the experiment, I get the following: 

Failed to write experiment, Index: 0, Size: 0

with Stack Trace ending with:

Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at autoweka.Parameter.<init>(Parameter.java:110)
	....

The issue appears in both SMAC and Random Search on several machines, but not TPE.

**Comment by DraXus** [comment]
Thanks for reporting @skocbek. It's been fixed already. Please feel free to re-open the ticket if this happens again.
